// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssociateCharacter } from "./AssociateCharacter";
import type { AssociateSaveDir } from "./AssociateSaveDir";

export type AssociateInfo = { characters: Array<AssociateCharacter>, save_dirs: Array<AssociateSaveDir>, };
