// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterInfo } from "./CharacterInfo";
import type { SaveDirInfo } from "./SaveDirInfo";

export type AssociateInfo = { characters: Array<CharacterInfo>, save_dirs: Array<SaveDirInfo>, };
