// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthorInfo = { author_id: number, author_name: string, author_account: string, count: number | null, };
