// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollectSummary = { id: number, series: string | null, character: string | null, before_count: number, after_count: number, collect_dir: string | null, unsave: boolean, };
