// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollectSummary = { id: number, series_tag: string | null, character_tag: string, before_count: number, after_count: number, new_path: string | null, is_new: boolean, };
