// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDetail } from "./FileDetail";
import type { IdInfo } from "./IdInfo";

export type DirDetail = { id_info: Array<IdInfo>, file_details: Array<FileDetail>, };
