// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditTag } from "./EditTag";

export type EditTagReq = { vec: Array<EditTag>, overwrite_tags: Array<string> | null, };
