// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvConfig = { REFRESH_TOKEN: string, INTERVAL_MILL_SEC: string, DB_NAME: string, };
