// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderCount } from "./FolderCount";

export type FileCounts = { folders: Array<FolderCount>, total: number, processing_time: string, };
