// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileDetail = { id: number, suffix: number, save_dir: string, extension: string, created_time: bigint, file_size: bigint, };
