// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessStats = { total_files: number, failed_files: number, process_time: string, failed_file_paths: Array<string>, };
