// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessStats = { total_ids: number, successed_ids: number, failed_ids: number, process_time: string, failed_file_paths: Array<string>, };
