// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorInfo } from "./AuthorInfo";

export type SearchResult = { id: number, file_name: string, thumbnail_url: string, author: AuthorInfo, character: string | null, save_dir: string, update_time: string, tags: string | null, };
