// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorInfo } from "./AuthorInfo";

export type SearchHistory = { tags: Array<string>, character: string | null, author: AuthorInfo | null, timestamp: string, result_count: number, };
