// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchResult = { illust_id: number, file_name: string, thumbnail_url: string, author_name: string, character: string | null, save_dir: string, tags: string | null, };
