// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagAssignment = { id: number, series_tag: string | null, character_tag: string | null, };
