// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagFixRuleAction } from "./TagFixRuleAction";

export type TagFixRule = { id: number, src_tag: string, dst_tag: string | null, action_type: TagFixRuleAction, created_at: string, };
