// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagProgress = { success: number, fail: number, current: number, total: number, elapsed_time: string, remaining_time: string, };
